### ISSUE TITLE
Frontend available?

### ISSUE THREAD

**Issue by dehlen** [joshua-stauffer/opening-book-api#6]
Hey, I just came across this repo and it looks really promising. Unfortunately I can't reach the site openingbook.org and can't find the frontend you are talking about in the README.
Would you mind sharing it open source as well?

I would really like to pick up the work on this project.

Kind regards,
David

**Comment by joshua-stauffer** [comment]
Hi David, thanks for reaching out, and for the interest! The FE component for this is pretty rough, and in my opinion would need to be rebuild from scratch. I lost steam for this project when I discovered that [chess tempo](https://chesstempo.com/opening-training/) offers a free spaced-repetition opening trainer, which basically fit all of my requirements! Just in case you would still like to extend this project, I added you as a collaborator on the basic React app, so feel free to check out the code.

My original plan was to build this as an add-on to Lichess, since that community is so amazing. I'm pretty busy these days with work on Great Expectations and the History Atlas, but would be happy to chip in from time to time, if you decide to pick this up!

**Comment by dehlen** [comment]
Hey thanks for your quick answer and the invitation. I use chess tempo my self and quite like it. However some parts (especially the mobile UI) I think could be improved which is why I thought I'd tackle this problem. Again thanks for your quick reply and I'll have a look at the repo.
